  # VCM Configuration
  # Please read the https://luckperms.net/wiki/Prefixes,-Suffixes-&-Meta before you set up.
  #
  # Placeholders:
  # {message} - the chat message
  # {name} - the player's name
  # {displayname} - the player's display name / nickname
  # {world} - the world name of the player's current world
  # {prefix} - the player's highest priority prefix
  # {suffix} - the player's highest priority suffix
  # {prefixes} - the player's prefixes sorted by the highest priority
  # {suffixes} - the player's suffixes sorted by the highest priority
  # {username-color} - the player's or the group's username color
  # {message-color} - the player's or the group's message color
  # {pronouns} - the player's pronouns (if set)
  #
  # To reload the configuration, run '/vcm reload' command. Make sure you have the 'vcm.reload' permission assigned.

  # More Info Can be found on the wiki: http://157.173.96.135:6041/lol/

  chat-format: "{prefix}{name}&r: {message}"

  # Set the format per group.
  # Note: Option for more advanced users. Remove comments to run.
  # group-formats:
  #   default: "[default] {displayname}&r ({pronouns}): {message}"
  #   admin: "[admin] {displayname}&r ({pronouns}): {message}"

  # Custom chat formats by permission
  # Note: Option for more advanced users. Remove comments to run.
  # permission-formats:
  #   vcm.chat.vip: "&6[VIP] {prefix}{displayname}&r ({pronouns}): {message}"
  #   vcm.chat.mod: "&2[MOD] {prefix}{displayname}&r ({pronouns}): {message}"

  # Nickname configuration
  nickname:
    min-length: 1
    max-length: 16

  # Anti-spam configuration
  chat-cooldown: 3  # Cooldown in seconds between chat messages
